const tokenNames = [
    "Optimism",
    "Arbitrum",
    "Polygon",
    "Ethereum",
    "Lido",
    "Uniswap",
    "Maker",
    "Aave",
    "curve-dex",
    "Compound",
    "Synthetix",
    "Liquity",
    "Kyberswap-Elastic",
    "Chainlink",
    "Avalanche",
    "Fantom",
    "Gnosis",
    "Osmosis",
    "PancakeSwap",
    "Blur",
    "Convex Finance",
    "Lyra",
    "Perpetual Protocol",
    "SushiSwap",
];

module.exports = { tokenNames }

// "InstaDapp",